# RADIUS clients — static file + SQL (nas table)
# SQL clients from nas table via read_clients = yes in sql config

client localhost {
    ipaddr = 127.0.0.1
    secret = testing123
    shortname = local
    require_message_authenticator = no
}

client docker-net {
    ipaddr = 192.168.176.0/24
    secret = testing123
    shortname = docker-network
    require_message_authenticator = no
}
